### Frontend Dockerfile

# Use Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy files
COPY ./frontend /app

# Install dependencies
RUN pip install -r requirements.txt

# Expose port
EXPOSE 8501

# Command to run Streamlit
CMD ["streamlit", "run", "streamlit-app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
